In [5]:
import numpy as np 
x = [3,0] 
np.linalg.norm(x)

3.0

In [6]:
import numpy as np # Compute the direction of a vector x. 
def direction(x): 
    return x/np.linalg.norm(x)

u = np.array([3,1]) 
w = direction(u) 
print(w) # [0.6 , 0.8]

[0.9486833  0.31622777]


In [7]:
import math 
import numpy as np 
def geometric_dot_product(x,y, theta): 
    x_norm = np.linalg.norm(x) 
    y_norm = np.linalg.norm(y)
    return x_norm * y_norm * math.cos(math.radians(theta))

theta = 45 
x = [3,5] 
y = [8,2]
geometric_dot_product(x,y, theta)

34.00000000000001

In [8]:
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler

# Set random seed for reproducibility
np.random.seed(42)

## 1. Basic Matrix Operations

# Creating matrices
print("Creating matrices:")
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
B = np.array([[9, 8, 7], 
              [6, 5, 4], 
              [3, 2, 1]])
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Matrix addition
print("\nMatrix addition (A + B):")
print(A + B)

# Matrix subtraction
print("\nMatrix subtraction (A - B):")
print(A - B)

# Scalar multiplication
print("\nScalar multiplication (2 * A):")
print(2 * A)

# Matrix multiplication
print("\nMatrix multiplication (A @ B or np.matmul(A, B)):")
print(A @ B)
# Alternatively: np.matmul(A, B) or A.dot(B)

# Element-wise multiplication
print("\nElement-wise multiplication (A * B):")
print(A * B)


Creating matrices:
Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix addition (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix subtraction (A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Scalar multiplication (2 * A):
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix multiplication (A @ B or np.matmul(A, B)):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise multiplication (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [9]:
# Matrix transpose
print("\nTranspose of A (A.T):")
print(A.T)

# Matrix inverse (using NumPy's linalg module)
print("\nInverse of a matrix:")
C = np.array([[1, 2], [3, 4]])  # A is singular, so using a different matrix
C_inv = np.linalg.inv(C)
print("Matrix C:")
print(C)
print("Inverse of C:")
print(C_inv)
print("Verification (C @ C_inv ≈ I):")
print(C @ C_inv)

# Determinant
print("\nDeterminant of matrix C:")
det_C = np.linalg.det(C)
print(det_C)



Transpose of A (A.T):
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Inverse of a matrix:
Matrix C:
[[1 2]
 [3 4]]
Inverse of C:
[[-2.   1. ]
 [ 1.5 -0.5]]
Verification (C @ C_inv ≈ I):
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]

Determinant of matrix C:
-2.0000000000000004


In [10]:
print("\n\n--- EIGENVALUES AND EIGENVECTORS ---\n")

# Create a symmetric matrix for better visualization of eigenvectors
D = np.array([[2, -1, 0], 
              [-1, 2, -1], 
              [0, -1, 2]])

print("Matrix D (symmetric):")
print(D)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(D)

print("\nEigenvalues of D:")
print(eigenvalues)

print("\nEigenvectors of D (columns of the matrix):")
print(eigenvectors)

# Verify Av = λv for the first eigenvalue-eigenvector pair
first_eigenvalue = eigenvalues[0]
first_eigenvector = eigenvectors[:, 0]

print("\nVerification of Av = λv:")
print(f"Left side (D @ v): {D @ first_eigenvector}")
print(f"Right side (λ * v): {first_eigenvalue * first_eigenvector}")



--- EIGENVALUES AND EIGENVECTORS ---

Matrix D (symmetric):
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]

Eigenvalues of D:
[3.41421356 2.         0.58578644]

Eigenvectors of D (columns of the matrix):
[[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  5.09486455e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]

Verification of Av = λv:
Left side (D @ v): [-1.70710678  2.41421356 -1.70710678]
Right side (λ * v): [-1.70710678  2.41421356 -1.70710678]


In [11]:
## 3. Eigendecomposition

print("\n\n--- EIGENDECOMPOSITION ---\n")

# Eigendecomposition: A = PDP^(-1)
# where P is the matrix of eigenvectors and D is diagonal matrix of eigenvalues

# Create diagonal matrix of eigenvalues
D_eigen = np.diag(eigenvalues)

print("Diagonal matrix of eigenvalues:")
print(D_eigen)

# Compute P^(-1)
P_inv = np.linalg.inv(eigenvectors)

# Reconstruct original matrix
D_reconstructed = eigenvectors @ D_eigen @ P_inv

print("\nOriginal matrix D:")
print(D)
print("\nReconstructed matrix from eigendecomposition:")
print(D_reconstructed)
print("\nDifference (should be close to zero):")
print(D - D_reconstructed)



--- EIGENDECOMPOSITION ---

Diagonal matrix of eigenvalues:
[[3.41421356 0.         0.        ]
 [0.         2.         0.        ]
 [0.         0.         0.58578644]]

Original matrix D:
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]

Reconstructed matrix from eigendecomposition:
[[ 2.00000000e+00 -1.00000000e+00 -8.58450316e-16]
 [-1.00000000e+00  2.00000000e+00 -1.00000000e+00]
 [-7.67631909e-16 -1.00000000e+00  2.00000000e+00]]

Difference (should be close to zero):
[[ 1.33226763e-15 -7.77156117e-16  8.58450316e-16]
 [-8.88178420e-16  1.77635684e-15 -1.33226763e-15]
 [ 7.67631909e-16 -9.99200722e-16  4.44089210e-16]]
